CREATE TABLE PESSOAS
(
	ID INT IDENTITY, 
	NOME VARCHAR(200), 
	CONSTRAINT PK_PESSOA PRIMARY KEY (ID)
)

INSERT INTO PESSOAS (NOME) VALUES ('Pessoa Numero Um');
INSERT INTO PESSOAS (NOME) VALUES ('Pessoa Numero Dois');
INSERT INTO PESSOAS (NOME) VALUES ('Pessoa Numero Três');
INSERT INTO PESSOAS (NOME) VALUES ('Pessoa Numero Quatro');

